spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32768/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  servlet:
    context-path: /api

security:
  jwt:
    key: 4CBDAF98D3838423B4684F77757DB